# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        CoreBundle\Entity\Administradores:
            algorithm: plaintext

        Symfony\Component\Security\Core\User\User:
            algorithm: plaintext
        # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        chain_provider:
            chain:
                providers: [user_db]
        in_memory:
            memory: ~
        user_db:
            entity: { class: CoreBundle\Entity\Administradores }

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_admin:
             anonymous: ~
             pattern:  ^/admin/.*
             provider: user_db
             logout:
                 path:   /admin/logout
                 target: adminlogin
             form_login:
                 login_path: adminlogin
                 check_path: adminlogin
                 default_target_path: admin_home
                 always_use_default_target_path: true
                 target_path_parameter: admin_home

        main:
            anonymous: ~
            pattern:    ^/
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html

    access_control:
        - { path: ^/admin/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/.*, role: ROLE_ADMIN }