<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 3.0.3 (doctrine2-annotation) on 2017-07-10 11:37:38.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace CoreBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * CoreBundle\Entity\MapsDistribuidor
 *
 * @ORM\Entity()
 * @ORM\Table(name="MapsDistribuidor")
 */
class MapsDistribuidor
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="string", length=250, nullable=true)
     */
    protected $url;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    protected $nombre;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    protected $zona;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    protected $activo;

    /**
     * @Gedmo\Slug(separator="-", updatable=true, fields={"nombre"})
     *
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    protected $slug;

    /**
     * @ORM\Column(type="string", length=250, nullable=true)
     */
    protected $metakeys;

    /**
     * @ORM\Column(type="string", length=500, nullable=true)
     */
    protected $metadesc;

    /**
     * @Gedmo\Timestampable(on="create", field="creado")
     *
     * @ORM\Column(type="datetime")
     */
    protected $created_at;

    /**
     * @Gedmo\Timestampable(on="update", field="actualizado")
     *
     * @ORM\Column(type="datetime")
     */
    protected $updated_at;

    /**
     * @ORM\OneToMany(targetEntity="MapsDistribuidorDirectorio", mappedBy="mapsDistribuidor")
     * @ORM\JoinColumn(name="id", referencedColumnName="id_MapsDistribuidor", nullable=false)
     */
    protected $mapsDistribuidorDirectorios;

    public function __construct()
    {
        $this->mapsDistribuidorDirectorios = new ArrayCollection();
    }

    public function __toString() {
        return $this->nombre;
    }

    /**
     * Set the value of id.
     *
     * @param integer $id
     * @return \CoreBundle\Entity\MapsDistribuidor
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of url.
     *
     * @param string $url
     * @return \CoreBundle\Entity\MapsDistribuidor
     */
    public function setUrl($url)
    {
        $this->url = $url;

        return $this;
    }

    /**
     * Get the value of url.
     *
     * @return string
     */
    public function getUrl()
    {
        return $this->url;
    }

    /**
     * Set the value of nombre.
     *
     * @param string $nombre
     * @return \CoreBundle\Entity\MapsDistribuidor
     */
    public function setNombre($nombre)
    {
        $this->nombre = $nombre;

        return $this;
    }

    /**
     * Get the value of nombre.
     *
     * @return string
     */
    public function getNombre()
    {
        return $this->nombre;
    }

    /**
     * Set the value of zona.
     *
     * @param string $zona
     * @return \CoreBundle\Entity\MapsDistribuidor
     */
    public function setZona($zona)
    {
        $this->zona = $zona;

        return $this;
    }

    /**
     * Get the value of zona.
     *
     * @return string
     */
    public function getZona()
    {
        return $this->zona;
    }

    /**
     * Set the value of activo.
     *
     * @param boolean $activo
     * @return \CoreBundle\Entity\MapsDistribuidor
     */
    public function setActivo($activo)
    {
        $this->activo = $activo;

        return $this;
    }

    /**
     * Get the value of activo.
     *
     * @return boolean
     */
    public function getActivo()
    {
        return $this->activo;
    }

    /**
     * Set the value of slug.
     *
     * @param string $slug
     * @return \CoreBundle\Entity\MapsDistribuidor
     */
    public function setSlug($slug)
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * Get the value of slug.
     *
     * @return string
     */
    public function getSlug()
    {
        return $this->slug;
    }

    /**
     * Set the value of metakeys.
     *
     * @param string $metakeys
     * @return \CoreBundle\Entity\MapsDistribuidor
     */
    public function setMetakeys($metakeys)
    {
        $this->metakeys = $metakeys;

        return $this;
    }

    /**
     * Get the value of metakeys.
     *
     * @return string
     */
    public function getMetakeys()
    {
        return $this->metakeys;
    }

    /**
     * Set the value of metadesc.
     *
     * @param string $metadesc
     * @return \CoreBundle\Entity\MapsDistribuidor
     */
    public function setMetadesc($metadesc)
    {
        $this->metadesc = $metadesc;

        return $this;
    }

    /**
     * Get the value of metadesc.
     *
     * @return string
     */
    public function getMetadesc()
    {
        return $this->metadesc;
    }

    /**
     * Set the value of created_at.
     *
     * @param \DateTime $created_at
     * @return \CoreBundle\Entity\MapsDistribuidor
     */
    public function setCreatedAt($created_at)
    {
        $this->created_at = $created_at;

        return $this;
    }

    /**
     * Get the value of created_at.
     *
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    /**
     * Set the value of updated_at.
     *
     * @param \DateTime $updated_at
     * @return \CoreBundle\Entity\MapsDistribuidor
     */
    public function setUpdatedAt($updated_at)
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    /**
     * Get the value of updated_at.
     *
     * @return \DateTime
     */
    public function getUpdatedAt()
    {
        return $this->updated_at;
    }

    /**
     * Add MapsDistribuidorDirectorio entity to collection (one to many).
     *
     * @param \CoreBundle\Entity\MapsDistribuidorDirectorio $mapsDistribuidorDirectorio
     * @return \CoreBundle\Entity\MapsDistribuidor
     */
    public function addMapsDistribuidorDirectorio(MapsDistribuidorDirectorio $mapsDistribuidorDirectorio)
    {
        $this->mapsDistribuidorDirectorios[] = $mapsDistribuidorDirectorio;

        return $this;
    }

    /**
     * Remove MapsDistribuidorDirectorio entity from collection (one to many).
     *
     * @param \CoreBundle\Entity\MapsDistribuidorDirectorio $mapsDistribuidorDirectorio
     * @return \CoreBundle\Entity\MapsDistribuidor
     */
    public function removeMapsDistribuidorDirectorio(MapsDistribuidorDirectorio $mapsDistribuidorDirectorio)
    {
        $this->mapsDistribuidorDirectorios->removeElement($mapsDistribuidorDirectorio);

        return $this;
    }

    /**
     * Get MapsDistribuidorDirectorio entity collection (one to many).
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getMapsDistribuidorDirectorios()
    {
        return $this->mapsDistribuidorDirectorios;
    }

    public function __sleep()
    {
        return array('id', 'url', 'nombre', 'zona', 'activo', 'slug', 'metakeys', 'metadesc', 'created_at', 'updated_at');
    }
}