<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 3.0.3 (doctrine2-annotation) on 2017-07-10 11:37:38.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace CoreBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * CoreBundle\Entity\MapsDistribuidorDirectorio
 *
 * @ORM\Entity()
 * @ORM\Table(name="MapsDistribuidorDirectorio", indexes={@ORM\Index(name="fk_MapsDistribuidorDirectorio_MapsDistribuidor1_idx", columns={"id_MapsDistribuidor"})})
 */
class MapsDistribuidorDirectorio
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="string", length=10, nullable=true)
     */
    protected $clave;

    /**
     * @ORM\Column(type="string", length=150, nullable=true)
     */
    protected $nombreDistribuidor;

    /**
     * @ORM\Column(type="string", length=300, nullable=true)
     */
    protected $direccion;

    /**
     * @ORM\Column(type="string", length=20, nullable=true)
     */
    protected $telefono;

    /**
     * @ORM\Column(type="string", length=20, nullable=true)
     */
    protected $whatsapp;

    /**
     * @ORM\Column(type="string", length=75, nullable=true)
     */
    protected $email;

    /**
     * @ORM\Column(type="string", length=75, nullable=true)
     */
    protected $email2;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    protected $orden;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    protected $activo;

    /**
     * @Gedmo\Timestampable(on="create", field="creado")
     *
     * @ORM\Column(type="datetime")
     */
    protected $created_at;

    /**
     * @Gedmo\Timestampable(on="update", field="actualizado")
     *
     * @ORM\Column(type="datetime")
     */
    protected $updated_at;

    /**
     * @ORM\ManyToOne(targetEntity="MapsDistribuidor", inversedBy="mapsDistribuidorDirectorios")
     * @ORM\JoinColumn(name="id_MapsDistribuidor", referencedColumnName="id", nullable=false)
     */
    protected $mapsDistribuidor;

    public function __construct()
    {
    }

    /**
     * Set the value of id.
     *
     * @param integer $id
     * @return \CoreBundle\Entity\MapsDistribuidorDirectorio
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of clave.
     *
     * @param string $clave
     * @return \CoreBundle\Entity\MapsDistribuidorDirectorio
     */
    public function setClave($clave)
    {
        $this->clave = $clave;

        return $this;
    }

    /**
     * Get the value of clave.
     *
     * @return string
     */
    public function getClave()
    {
        return $this->clave;
    }

    /**
     * Set the value of nombreDistribuidor.
     *
     * @param string $nombreDistribuidor
     * @return \CoreBundle\Entity\MapsDistribuidorDirectorio
     */
    public function setNombreDistribuidor($nombreDistribuidor)
    {
        $this->nombreDistribuidor = $nombreDistribuidor;

        return $this;
    }

    /**
     * Get the value of nombreDistribuidor.
     *
     * @return string
     */
    public function getNombreDistribuidor()
    {
        return $this->nombreDistribuidor;
    }

    /**
     * Set the value of direccion.
     *
     * @param string $direccion
     * @return \CoreBundle\Entity\MapsDistribuidorDirectorio
     */
    public function setDireccion($direccion)
    {
        $this->direccion = $direccion;

        return $this;
    }

    /**
     * Get the value of direccion.
     *
     * @return string
     */
    public function getDireccion()
    {
        return $this->direccion;
    }

    /**
     * Set the value of telefono.
     *
     * @param string $telefono
     * @return \CoreBundle\Entity\MapsDistribuidorDirectorio
     */
    public function setTelefono($telefono)
    {
        $this->telefono = $telefono;

        return $this;
    }

    /**
     * Get the value of telefono.
     *
     * @return string
     */
    public function getTelefono()
    {
        return $this->telefono;
    }

    /**
     * Set the value of whatsapp.
     *
     * @param string $whatsapp
     * @return \CoreBundle\Entity\MapsDistribuidorDirectorio
     */
    public function setWhatsapp($whatsapp)
    {
        $this->whatsapp = $whatsapp;

        return $this;
    }

    /**
     * Get the value of whatsapp.
     *
     * @return string
     */
    public function getWhatsapp()
    {
        return $this->whatsapp;
    }

    /**
     * Set the value of email.
     *
     * @param string $email
     * @return \CoreBundle\Entity\MapsDistribuidorDirectorio
     */
    public function setEmail($email)
    {
        $this->email = $email;

        return $this;
    }

    /**
     * Get the value of email.
     *
     * @return string
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * Set the value of email2.
     *
     * @param string $email2
     * @return \CoreBundle\Entity\MapsDistribuidorDirectorio
     */
    public function setEmail2($email2)
    {
        $this->email2 = $email2;

        return $this;
    }

    /**
     * Get the value of email2.
     *
     * @return string
     */
    public function getEmail2()
    {
        return $this->email2;
    }

    /**
     * Set the value of orden.
     *
     * @param integer $orden
     * @return \CoreBundle\Entity\MapsDistribuidorDirectorio
     */
    public function setOrden($orden)
    {
        $this->orden = $orden;

        return $this;
    }

    /**
     * Get the value of orden.
     *
     * @return integer
     */
    public function getOrden()
    {
        return $this->orden;
    }

    /**
     * Set the value of activo.
     *
     * @param boolean $activo
     * @return \CoreBundle\Entity\MapsDistribuidorDirectorio
     */
    public function setActivo($activo)
    {
        $this->activo = $activo;

        return $this;
    }

    /**
     * Get the value of activo.
     *
     * @return boolean
     */
    public function getActivo()
    {
        return $this->activo;
    }

    /**
     * Set the value of created_at.
     *
     * @param \DateTime $created_at
     * @return \CoreBundle\Entity\MapsDistribuidorDirectorio
     */
    public function setCreatedAt($created_at)
    {
        $this->created_at = $created_at;

        return $this;
    }

    /**
     * Get the value of created_at.
     *
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    /**
     * Set the value of updated_at.
     *
     * @param \DateTime $updated_at
     * @return \CoreBundle\Entity\MapsDistribuidorDirectorio
     */
    public function setUpdatedAt($updated_at)
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    /**
     * Get the value of updated_at.
     *
     * @return \DateTime
     */
    public function getUpdatedAt()
    {
        return $this->updated_at;
    }

    /**
     * Set MapsDistribuidor entity (many to one).
     *
     * @param \CoreBundle\Entity\MapsDistribuidor $mapsDistribuidor
     * @return \CoreBundle\Entity\MapsDistribuidorDirectorio
     */
    public function setMapsDistribuidor(MapsDistribuidor $mapsDistribuidor = null)
    {
        $this->mapsDistribuidor = $mapsDistribuidor;

        return $this;
    }

    /**
     * Get MapsDistribuidor entity (many to one).
     *
     * @return \CoreBundle\Entity\MapsDistribuidor
     */
    public function getMapsDistribuidor()
    {
        return $this->mapsDistribuidor;
    }

    public function __sleep()
    {
        return array('id', 'id_MapsDistribuidor', 'clave', 'nombreDistribuidor', 'direccion', 'telefono', 'whatsapp', 'email', 'email2', 'orden', 'activo', 'created_at', 'updated_at');
    }
}